name: CI/CD Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  # Job 1: Analyse statique et qualité du code
  lint-and-format:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Check TypeScript types
        run: npx tsc --noEmit

      - name: Run ESLint
        run: npm run lint

      - name: Check for unused dependencies
        run: npx depcheck --ignores="@types/*,eslint-*,prettier,tailwindcss"

      - name: Security audit
        run: npm audit --audit-level=moderate

  # Job 2: Tests unitaires et d'intégration
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-latest
    needs: lint-and-format
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Setup test environment
        run: |
          echo "Setting up test environment..."
          cp .env.example .env.test || echo "No .env.example found"
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          NEXT_PUBLIC_BETTER_AUTH_URL: http://localhost:3000

      - name: Run database migrations
        run: npm run db:push
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test

      - name: Run unit tests
        run: npm run test:unit
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          NEXT_PUBLIC_BETTER_AUTH_URL: http://localhost:3000

      - name: Run integration tests
        run: npm run test:integration
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          NEXT_PUBLIC_BETTER_AUTH_URL: http://localhost:3000

      - name: Run security tests
        run: npm run test:security
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          BETTER_AUTH_SECRET: test-secret-key-for-ci
          NEXT_PUBLIC_BETTER_AUTH_URL: http://localhost:3000

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  # Job 3: Build et vérification
  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [lint-and-format, test]
    env:
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test
      BETTER_AUTH_SECRET: test-secret-key-for-ci
      NEXT_PUBLIC_BETTER_AUTH_URL: http://localhost:3000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build application
        run: npm run build

      - name: Check build size
        run: |
          echo "Build completed successfully"
          ls -la .next/static/

  # Job 4: Tests d'accessibilité (optionnel)
  accessibility-tests:
    name: Accessibility Tests
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'accessibility')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run accessibility tests
        run: npm run test:accessibility
        env:
          NEXT_PUBLIC_APP_URL: http://localhost:3000

  # Job 5: Notification et résumé
  notify:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [lint-and-format, test, build, accessibility-tests]
    if: always()
    steps:
      - name: Pipeline Status
        run: |
          echo "🚀 Pipeline Status:"
          echo "- Lint & Format: ${{ needs.lint-and-format.result }}"
          echo "- Tests (Unit/Integration/Security): ${{ needs.test.result }}"
          echo "- Build: ${{ needs.build.result }}"
          echo "- Accessibility Tests: ${{ needs.accessibility-tests.result || 'skipped' }}"
          
          if [[ "${{ needs.lint-and-format.result }}" == "success" && 
                "${{ needs.test.result }}" == "success" && 
                "${{ needs.build.result }}" == "success" ]]; then
            echo "✅ All core checks passed!"
            echo "📊 Test coverage and security checks completed"
          else
            echo "❌ Pipeline failed"
            exit 1
          fi