apiVersion: 1

groups:
  - name: athleteaxis-alerts
    orgId: 1
    folder: AthleteAxis
    interval: 1m
    rules:
      - uid: high-cpu-usage
        title: "CPU Usage élevé"
        condition: A
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus
            model:
              expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: "L'utilisation CPU est supérieure à 80% depuis plus de 2 minutes"
          summary: "CPU usage élevé détecté"
        labels:
          severity: warning
          team: devops

      - uid: high-memory-usage
        title: "Utilisation mémoire élevée"
        condition: A
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus
            model:
              expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 5m
        annotations:
          description: "L'utilisation mémoire est supérieure à 85% depuis plus de 5 minutes"
          summary: "Utilisation mémoire critique"
        labels:
          severity: critical
          team: devops

      - uid: high-response-time
        title: "Temps de réponse élevé"
        condition: A
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus
            model:
              expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le)) * 1000
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 3m
        annotations:
          description: "Le temps de réponse p95 est supérieur à 2000ms depuis plus de 3 minutes"
          summary: "Performances dégradées"
        labels:
          severity: warning
          team: backend

      - uid: high-error-rate
        title: "Taux d'erreur élevé"
        condition: A
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus
            model:
              expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) * 100
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 2m
        annotations:
          description: "Le taux d'erreur 5xx est supérieur à 5% depuis plus de 2 minutes"
          summary: "Taux d'erreur critique"
        labels:
          severity: critical
          team: backend

      - uid: database-connections
        title: "Trop de connexions DB"
        condition: A
        data:
          - refId: A
            queryType: ""
            relativeTimeRange:
              from: 300
              to: 0
            datasource:
              type: prometheus
              uid: prometheus
            model:
              expr: athlete_axis_database_connections
              refId: A
        noDataState: NoData
        execErrState: Alerting
        for: 1m
        annotations:
          description: "Le nombre de connexions à la base de données est anormalement élevé"
          summary: "Connexions DB élevées"
        labels:
          severity: warning
          team: backend